version: "3.0"
services:

    lineservice:
      container_name: lineservice
      build: LineService/
      ports:
      - "5000:5000"
      restart: on-failure

    accesstoken:
      container_name: accesstoken
      build: AccessToken/
      restart: on-failure

    sendnotify:
      container_name: sendnotify
      build: SendNotify/
      restart: on-failure
